import {MotorAccessories} from './motor-accessories';
import {Risk} from './risk';

export class Motor {

  FMV: string;
  isCorporate: string;
  productId: string;
  product: string;
  motorId: string;
  motorDescription: string;
  modelYear: string;
  manufacturer: string;
  manufacturerId: string;
  manufacturerIdHolder: string;
  model: string;
  modelId: string;
  modelIdHolder: string;
  subModel: string;
  subModelId: string;
  subModelIdHolder: string;
  transmission: string;
  transmissionId: string;
  transmissionIdHolder: string;
  fuel: string;
  fuelId: string;
  fuelIdHolder: string;
  drivetrain: string;
  drivetrainId: string;
  drivetrainIdHolder: string;
  motorType: string;
  motorTypeId: string;
  motorTypeIdHolder: string;
  vehicleType: string;
  vehicleTypeId: string;
  vehicleTypeIdHolder: string;
  vehicleUsed: string;
  vehicleUsedId: string;
  vehicleUsedIdHolder: string;
  usageArea: string;
  usageAreaId: string;
  usageAreaIdHolder: string;
  isMortgaged: boolean;
  mortgagee: string;
  mortgageeId: string;
  mortgageeIdHolder: string;
  policyPeriod: string;
  policyPeriodFrom: string;
  policyPeriodTo: string;
  motorNumber: string;
  serialNumber: string;
  plateNumber: string;
  txtMotivoSpto: string;
  conductionNumber: string;
  MVFileNumber: string;
  color: string;
  colorId: string;
  colorIdHolder: string;
  subline: string;
  validityDate: string;
  bodilyInjuryLimit: string;
  propertyDamageLimit: string;
  reCompute: string;
  accessories: MotorAccessories[] = [];
  directors: Risk[] = [];
  stockholders: Risk[] = [];
  beneficiaries: Risk[] = [];
  vehiclePhotos: File[] = [];
  
}